[versions]
androidGradlePlugin = "8.5.2"
moshi="1.15.1"
kotlin = "2.0.0"
coroutines = "1.8.1"
androidDesugarJdkLibs = "2.1.2"
androidXCore = "1.13.1"
androidXCompat = "1.7.0"
androidxComposeBom = "2024.09.00"
androidxActivity = "1.9.2"
constraintlayout = "2.1.4"
constraintlayoutCompose="1.0.1"
accompanist = "0.34.0"
composeNavigation = "2.8.0"
composeLifecycle = "2.8.5"
androidx-compose-material3 = "1.3.0"
androidx-compose-material3-adaptive = "1.0.0"
dagger="2.51.1"
hilt="1.2.0"
androidxHiltNavigationCompose="1.2.0"
junit = "5.9.3" # https://junit.org/junit5/docs/5.8.0/release-notes/
espresso = "3.5.1" # https://developer.android.com/jetpack/androidx/releases/test
mockito = "5.7.0" # https://github.com/mockito/mockito/releases
mockito_inline = "5.2.0"
mockito_kotlin = "5.0.0" # https://github.com/mockito/mockito-kotlin/releases
truth = "1.1.5" # https://github.com/google/truth/releases
turbine = "0.13.0" # https://github.com/cashapp/turbine/
retrofit = "2.11.0"
okhttp = "4.12.0"
detekt = "1.23.6"
versionsPlugin = "0.51.0"
leakCanary = "2.12"
lint = "31.0.0"
material = "1.12.0"
navigation = "2.8.0"
workManager = "2.9.1"
datastore = "1.1.1"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidXCore" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidXCore" }
android-compat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidXCompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity"}
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-window = { group = "androidx.compose.material3", name = "material3-window-size-class" }

androidx-compose-material3-adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version.ref = "androidx-compose-material3-adaptive" }
androidx-compose-material3-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout", version.ref = "androidx-compose-material3-adaptive" }
androidx-compose-material3-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation", version.ref = "androidx-compose-material3-adaptive" }
androidx-compose-material3-adaptive-navigationSuite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite", version.ref = "androidx-compose-material3" }
androidx-compose-material-iconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core" }

androidx-accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist"}
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
androidx-lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "composeLifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "composeLifecycle" }
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "hilt" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-inline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockito_inline" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito_kotlin" }
mockito-android = { group = "org.mockito", name = "mockito-android", version.ref = "mockito" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
moshi-adapters = { group = "com.squareup.moshi", name = "moshi-adapters", version.ref = "moshi" }
moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
okhttp-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt"}
leak-canary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakCanary" }
material = { group = "com.google.android.material", name = "material", version.ref = "material"}
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation"}
navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation"}
work-manager-runtime = { group = "androidx.work", name="work-runtime", version.ref = "workManager"}
datastore = { group = "androidx.datastore", name="datastore", version.ref = "datastore"}
datastore-preferences = { group = "androidx.datastore", name="datastore-preferences", version.ref = "datastore"}
datastore-core = { group = "androidx.datastore", name="datastore-core", version.ref = "datastore" }

[bundles]
ui = ["androidx-core", "androidx-core-ktx", "android-compat", "androidx-constraintlayout"]
old-ui = ["material", "navigation-fragment", "navigation-ui"]
compose-ui = ["androidx-compose-ui", "androidx-compose-animation", "androidx-compose-foundation", "androidx-compose-material3", "androidx-compose-material3-window", "androidx-accompanist-systemuicontroller", "androidx-compose-ui-tooling", "androidx-compose-ui-tooling-preview", "androidx-navigation-compose", "androidx-lifecycle-compose", "androidx-lifecycle-runtime-compose", "androidx-constraintlayout-compose", "androidx-compose-material", "androidx-compose-material3-adaptive-navigation", "androidx-compose-material3-adaptive-layout", "androidx-compose-material3-adaptive", "androidx-compose-material3-adaptive-navigationSuite", "androidx-compose-material-iconsExtended", "androidx-material-icons-core"]
test = ["coroutines-test", "junit-api", "junit-params", "mockito-core", "mockito-inline", "mockito-kotlin", "truth", "turbine"]
network = ["moshi-adapters", "okhttp", "okhttp-logging", "retrofit", "retrofit-moshi"]
debug =  ["leak-canary"]
work-manager = ["work-manager-runtime"]
hilt = ["dagger-hilt-android", "hilt-common", "hilt-work", "androidx-hilt-navigation-compose"]
datastore = ["datastore", "datastore-preferences", "datastore-core"]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin"}
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
